-- Usuarios
INSERT INTO Usuario (nombre, apellidos, nickname, contrasenha, email, fecha_nacimiento,plan_suscripcion)
VALUES ('Rafael', 'Martinez Valero', 'Rafa33', '1234', 'rafael@example.com', '1990-05-15','Gratis');

INSERT INTO Usuario (nombre, apellidos, nickname, contrasenha, email, fecha_nacimiento,plan_suscripcion)
VALUES ('Maria', 'Casas Gonzalez', 'Maria33', '12345', 'maria@example.com', '1985-09-22','Pro');

INSERT INTO Usuario (nombre, apellidos, nickname, contrasenha, email, fecha_nacimiento,plan_suscripcion)
VALUES ('Carlos', 'Rodriguez Sanz', 'Carlos33', '12345', 'carlos@example.com', '1995-12-10','Pro');

-- Contenido en directo

INSERT INTO live_content (nombre_contenido, descripcion, anho, url_image, url_video, start_time, end_time, type)
VALUES ('El Padrino', 'Un poderoso drama criminal que sigue la vida de la familia Corleone en el mundo del crimen organizado.', 2024, 'images/Peliculas/ElPadrino.jpeg', 'https://www.youtube.com/embed/iOyQx7MXaz0?si=nuCJfNniJoPzuQTb', '2024-04-19T19:30:00', '2024-04-19T20:00:00', 'Pelicula en directo');

INSERT INTO live_content (nombre_contenido, descripcion, anho, url_image, url_video, start_time, end_time, type)
VALUES ('Cars 3', 'Con una nueva generación de corredores amenazando su posición, Rayo McQueen se embarca en un emocionante viaje de redescubrimiento y superación. Con la ayuda de entrenadores y nuevos amigos, Rayo intenta volver al ruedo y dejar su marca.', 2024, 'images/Peliculas/Cars3.png', 'https://www.youtube.com/embed/wtmW9rSRIzU?si=MttED7g2UgQk5A08', '2024-04-18T19:20:00', '2024-04-18T19:25:00', 'Pelicula en directo');

INSERT INTO live_content (nombre_contenido, descripcion, anho, url_image, url_video, start_time, end_time, type)
VALUES ('Cars', 'Rayo McQueen y su amigo Mate se ven envueltos en una misión internacional de espionaje cuando son reclutados para participar en el Grand Prix Mundial. Intrigas, giros y vueltas esperan a nuestros héroes mientras luchan contra una misteriosa amenaza.', 2024, 'images/Peliculas/Cars.png', 'https://www.youtube.com/embed/wtmW9rSRIzU?si=MttED7g2UgQk5A08', '2024-04-20T19:00:00', '2024-04-20T19:30:00', 'Pelicula en directo');

INSERT INTO live_content (nombre_contenido, descripcion, anho, url_image, url_video, start_time, end_time, type)
VALUES ('Cars 2', 'En un mundo donde los autos son seres vivos, el aspirante a corredor Rayo McQueen termina en un pequeño pueblo llamado Radiador Springs. Aprendiendo lecciones valiosas de amistad y humildad, Rayo descubre el verdadero significado de la velocidad.', 2024, 'images/Peliculas/Cars2.png', 'https://www.youtube.com/embed/wtmW9rSRIzU?si=MttED7g2UgQk5A08', '2024-04-21T19:00:00', '2024-04-21T19:05:00', 'Pelicula en directo');


-- Películas
INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Padrino', 'Un poderoso drama criminal que sigue la vida de la familia Corleone en el mundo del crimen organizado.', 'Il Padrino', 'Crimen, Drama', 'Estados Unidos', 175, 1972, 'Paramount Pictures', 'Francis Ford Coppola', 18, 'Ganadora de 3 premios Oscar.', 'Marlon Brando, Al Pacino, James Caan','images/Peliculas/ElPadrino.jpeg', 'https://www.youtube.com/embed/iOyQx7MXaz0?si=nuCJfNniJoPzuQTb', 7.8);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Cadena Perpetua', 'La historia de un hombre inocente encarcelado que encuentra esperanza y amistad en Shawshank.',  'Shawshank Redemption', 'Drama', 'Estados Unidos', 142, 1994, 'Columbia Pictures', 'Frank Darabont', 15, 'Basada en la novela de Stephen King.', 'Tim Robbins, Morgan Freeman', 'images/Peliculas/CadenaPerpetua.jpeg', 'https://www.youtube.com/embed/4u87tmlj4oE?si=n318897_-rDPVLzP', 9.3);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Caballero Oscuro', 'Batman se enfrenta a su némesis, el Joker, en un juego de ingenio que amenaza Gotham City.', 'The Dark Knight', 'Accion, Crimen, Drama', 'Estados Unidos', 152, 2008, 'Warner Bros.', 'Christopher Nolan', 16, 'Ganadora de 2 premios Oscar.', 'Christian Bale, Heath Ledger, Aaron Eckhart', 'images/Peliculas/CaballeroOscuro.jpeg', 'https://www.youtube.com/embed/9MEuGQtM9wA?si=A5YSZGVuwDCtK83o', 9.0);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Cars', 'En un mundo donde los autos son seres vivos, el aspirante a corredor Rayo McQueen termina en un pequeño pueblo llamado Radiador Springs. Aprendiendo lecciones valiosas de amistad y humildad, Rayo descubre el verdadero significado de la velocidad.', 'Cars', 'Animacion', 'Estadounidense', 120, 2006, 'Pixar', 'John Lasseter', 3, 'Datos adicionales sobre la película Cars.', 'Owen Wilson, Bonnie Hunt', 'images/Peliculas/Cars.png', 'https://www.youtube.com/embed/nuQDFYpPUh4?si=owxKwSIVF6QzUeh1', 7.1);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Cars 2', 'Rayo McQueen y su amigo Mate se ven envueltos en una misión internacional de espionaje cuando son reclutados para participar en el Grand Prix Mundial. Intrigas, giros y vueltas esperan a nuestros héroes mientras luchan contra una misteriosa amenaza.', 'Cars 2', 'Animacion', 'Estadounidense', 130, 2011, 'Pixar', 'John Lasseter', 3, 'Datos adicionales sobre la película Cars 2.', 'Owen Wilson, Larry the Cable Guy', 'images/Peliculas/Cars2.png', 'https://www.youtube.com/embed/oGpIMRq1O3k?si=UUSOoOjMZg_RPptk', 6.2);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Cars 3', 'Con una nueva generación de corredores amenazando su posición, Rayo McQueen se embarca en un emocionante viaje de redescubrimiento y superación. Con la ayuda de entrenadores y nuevos amigos, Rayo intenta volver al ruedo y dejar su marca.', 'Cars 3', 'Animacion', 'Estadounidense', 110, 2017, 'Pixar', 'Brian Fee', 3, 'Datos adicionales sobre la película Cars 3.', 'Owen Wilson, Cristela Alonzo', 'images/Peliculas/Cars3.png', 'https://www.youtube.com/embed/wtmW9rSRIzU?si=MttED7g2UgQk5A08', 6.5);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Kung Fu Panda', 'Po, un torpe oso panda, sueña con convertirse en un hábil guerrero de kung fu. Su vida da un giro cuando es elegido accidentalmente para cumplir una antigua profecía. Po se embarca en una aventura cómica y emocionante para aprender las artes marciales y salvar el Valle de la Paz.',  'Kung Fu Panda', 'Animacion', 'Estadounidense', 95, 2008, 'DreamWorks Animation', 'Mark Osborne, John Stevenson', 3, 'Datos adicionales sobre la película Kung Fu Panda.', 'Jack Black, Angelina Jolie', 'images/Peliculas/KunfuPanda.png', 'https://www.youtube.com/embed/vRhMIpFu-Zw?si=Hwgor3iZaTcqtmz4', 8.0);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('One Piece', 'Monkey D. Luffy y su valiente tripulación emprenden un viaje épico en busca del legendario tesoro conocido como "One Piece". Enfrentándose a peligros, enemigos y desafíos, Luffy se esfuerza por convertirse en el Rey de los Piratas.', 'One Piece', 'Animacion', 'Japonesa', 120, 2022, 'Toei Animation', 'Eiichiro Oda', 12, 'Datos adicionales sobre la película One Piece.', 'Mayumi Tanaka, Kazuya Nakai', 'images/Peliculas/OnePiece.png', 'https://www.youtube.com/embed/CWrJQzm0diI?si=tzF0AIbtEib0kGCV', 8.5);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Rocky', 'Rocky Balboa, un boxeador de Filadelfia con pocas oportunidades, recibe la oportunidad de enfrentarse al campeón de peso pesado Apollo Creed. Aunque inicialmente es considerado como un oponente fácil, Rocky se prepara para la pelea de su vida, demostrando coraje y determinación.',  'Rocky', 'Drama', 'Estadounidense', 120, 1976, 'United Artists', 'John G. Avildsen', 12, 'Datos adicionales sobre la película Rocky.', 'Sylvester Stallone, Talia Shire, Burgess Meredith', 'images/Peliculas/Rocky.png', 'https://www.youtube.com/embed/Vb-Bx2YkIPA?si=UZigoaMfxKRR6Hy8', 8.1);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Harry Potter y la Piedra Filosofal', 'Harry Potter, un niño huérfano, descubre que es un mago y comienza su educación en la escuela de magia de Hogwarts. Junto a sus amigos, enfrenta misterios y descubre la verdad sobre su pasado.', 'Harry Potter and the Philosophers Stone', 'Aventura, Familia, Fantasia', 'Reino Unido', 152, 2001, 'Warner Bros.', 'Chris Columbus', 7, 'Basada en la novela de J.K. Rowling.', 'Daniel Radcliffe, Emma Watson, Rupert Grint', 'images/Peliculas/potter.png', 'https://www.youtube.com/embed/VyHV0BRtdxo?si=3DCTwOj-S_GY1s_X', 8.7);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Matrix', 'Neo, un hacker, descubre que vive en un simulacro y se une a una rebelión contra las máquinas que controlan la realidad. Una historia de ciencia ficcion llena de acción y reflexión filosófica.',  'The Matrix', 'Accion, Ciencia Ficcion', 'Estados Unidos', 136, 1999, 'Warner Bros.', 'Lana Wachowski, Lilly Wachowski', 15, 'Ganadora de 4 premios Oscar.', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'images/Peliculas/Matrix.png', 'https://www.youtube.com/embed/m8e-FF8MsqU?si=LKyR-3B4Q2qFD0Js', 8.7);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Jurassic Park', 'Un parque temático con dinosaurios creados mediante ingeniería genética se convierte en una pesadilla cuando los animales escapan y amenazan a los visitantes. Una aventura llena de suspense y emoción.', 'Jurassic Park', 'Aventura, Ciencia Ficcion', 'Estados Unidos', 127, 1993, 'Universal Pictures', 'Steven Spielberg', 12, 'Basada en la novela de Michael Crichton.', 'Sam Neill, Laura Dern, Jeff Goldblum', 'images/Peliculas/JurassicPark.jpg', 'https://www.youtube.com/embed/lc0UehYemQA?si=UqjSjLRnQ4S4izZk', 8.4);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Titanic', 'La historia de amor entre Jack y Rose se desarrolla a bordo del Titanic, el famoso transatlántico que choca con un iceberg y enfrenta un trágico destino. Una épica romántica y dramática.',  'Titanic', 'Drama, Romance', 'Estados Unidos', 195, 1997, '20th Century Fox', 'James Cameron', 12, 'Ganadora de 11 premios Oscar.', 'Leonardo DiCaprio, Kate Winslet', 'images/Peliculas/Titanic.jpg', 'https://www.youtube.com/embed/2e-eXJ6HgkQ?si=IctQRBQoTeKUh86p', 8.8);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Forrest Gump', 'Forrest Gump, un hombre con un coeficiente intelectual bajo, vive una vida extraordinaria llena de aventuras, amor y acontecimientos históricos.', 'Forrest Gump', 'Drama, Romance', 'Estados Unidos', 142, 1994, 'Paramount Pictures', 'Robert Zemeckis', 12, 'Basada en la novela de Winston Groom.', 'Tom Hanks, Robin Wright, Gary Sinise', 'images/Peliculas/ForrestGump.jpg', 'https://www.youtube.com/embed/uPIEn0M8su0?si=fLm5qE9BQMWXx6oS', 7.7);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('Interestelar', 'Un equipo de astronautas se embarca en un viaje a través de un agujero de gusano en busca de un nuevo hogar para la humanidad. Una odisea espacial llena de misterio y descubrimiento.', 'Interstellar', 'Aventura, Drama, Ciencia Ficcion', 'Estados Unidos', 169, 2014, 'Paramount Pictures', 'Christopher Nolan', 12, 'Ganadora del premio Oscar a los mejores efectos visuales.', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain', 'images/Peliculas/Interstellar.jpg', 'https://www.youtube.com/embed/zSWdZVtXT7E?si=4r2XsH2dSsO-0KKp', 8.4);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Rey León', 'Simba, un joven león, lucha por reclamar su lugar como rey después de que su malvado tío Scar usurpe el trono de su padre. Una épica historia de crecimiento, amor y responsabilidad.', 'The Lion King', 'Animacion, Aventura, Drama', 'Estados Unidos', 118, 1994, 'Walt Disney Pictures', 'Roger Allers, Rob Minkoff', 3, 'Inspirada en Hamlet de William Shakespeare.', 'Matthew Broderick, Jeremy Irons, James Earl Jones', 'images/Peliculas/LionKing.jpg', 'https://www.youtube.com/embed/4sj1MT05lAA?si=yBQKcF9tQoq6zF3a', 6.9);

INSERT INTO Pelicula (nombre_contenido, descripcion,  titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Señor de los Anillos: La Comunidad del Anillo', 'Frodo Bolsón, un hobbit tranquilo, se embarca en una aventura épica para destruir un anillo maligno y salvar a la Tierra Media del mal. Una saga de fantasía que redefine el género.',  'The Lord of the Rings: The Fellowship of the Ring', 'Aventura, Drama, Fantasia', 'Estados Unidos', 178, 2001, 'New Line Cinema', 'Peter Jackson', 12, 'Basada en la novela de J.R.R. Tolkien.', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 'images/Peliculas/LOTR1.jpg', 'https://www.youtube.com/embed/V75dMMIW2B4?si=OzZkPOklRZWaTpvl', 8.3);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Silencio de los Inocentes', 'Un joven agente del FBI busca la ayuda de Hannibal Lecter, un brillante pero peligroso psiquiatra encarcelado, para atrapar a un asesino en serie. Un thriller psicológico que te mantendrá al borde de tu asiento.',  'The Silence of the Lambs', 'Crimen, Drama, Thriller', 'Estados Unidos', 118, 1991, 'Orion Pictures', 'Jonathan Demme', 18, 'Basada en la novela de Thomas Harris.', 'Jodie Foster, Anthony Hopkins, Scott Glenn', 'images/Peliculas/SilenceoftheLambs.jpg', 'https://www.youtube.com/embed/W6Mm8Sbe__o?si=tT_TQOD3RfG2V2tJ', 7.2);

INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('La La Land', 'Un pianista de jazz y una aspirante a actriz se enamoran en Los Ángeles mientras persiguen sus sueños. Una historia de amor y ambición ambientada en la vibrante ciudad de las estrellas.', 'La La Land', 'Comedia, Drama, Musical', 'Estados Unidos', 128, 2016, 'Summit Entertainment', 'Damien Chazelle', 7, 'Ganadora de 6 premios Oscar.', 'Ryan Gosling, Emma Stone, John Legend', 'images/Peliculas/LaLaLand.jpg', 'https://www.youtube.com/embed/0pdqf4P9MB8?si=Tw-k8yPtTsmfqEUv', 7.8);

-- Película 1: El Corredor del Laberinto
INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Corredor del Laberinto', 'Un joven despierta en un ascensor con amnesia rodeado de un grupo de jóvenes en un claro rodeado por un laberinto impenetrable. Pronto aprenden que deben unir fuerzas para escapar del laberinto y descubrir quiénes son y por qué están ahí.', 'The Maze Runner', 'Acción, Ciencia Ficción, Aventura', 'Estados Unidos', 113, 2014, '20th Century Fox', 'Wes Ball', 12, 'Basada en la novela de James Dashner.', 'Dylan O Brien, Kaya Scodelario, Thomas Brodie-Sangster', 'images/Peliculas/MazeRunner.jpg', 'https://www.youtube.com/embed/AwwbhhjQ9Xk', 7.2);

-- Película 2: El Corredor del Laberinto: Prueba de Fuego
INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Corredor del Laberinto: Prueba de Fuego', 'Thomas y sus amigos se enfrentan a su mayor desafío hasta ahora: buscar pistas sobre la misteriosa y poderosa organización conocida como C.R.U.E.L. Su viaje les lleva a La Quemadura, un paisaje desolado lleno de obstáculos inimaginables.', 'Maze Runner: The Scorch Trials', 'Acción, Ciencia Ficción, Aventura', 'Estados Unidos', 131, 2015, '20th Century Fox', 'Wes Ball', 12, 'Secuela de El Corredor del Laberinto.', 'Dylan O Brien, Kaya Scodelario, Thomas Brodie-Sangster', 'images/Peliculas/MazeRunnerScorchTrials.jpg', 'https://www.youtube.com/embed/-44_igsZtgU', 6.3);

-- Película 3: El Corredor del Laberinto: La Cura Mortal
INSERT INTO Pelicula (nombre_contenido, descripcion, titulo_original, genero, nacionalidad, duracion, anho, distribuidora, director, clasificacion_edad, otros_datos, actores, url_image, url_video, calificacion)
VALUES ('El Corredor del Laberinto: La Cura Mortal', 'Thomas lidera a su grupo de rescatados de las mazmorras a la última y más peligrosa misión. Para salvar a sus amigos, deben entrar en la legendaria Última Ciudad, un laberinto controlado por WCKD que puede resultar ser el laberinto más mortífero de todos.', 'Maze Runner: The Death Cure', 'Acción, Ciencia Ficción, Aventura', 'Estados Unidos', 143, 2018, '20th Century Fox', 'Wes Ball', 12, 'Última entrega de la trilogía.', 'Dylan O Brien, Kaya Scodelario, Thomas Brodie-Sangster', 'images/Peliculas/MazeRunnerDeathCure.jpg', 'https://www.youtube.com/embed/S_9OSktlm6s', 6.2);



-- F1 Content
-- 2005
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2005', 'El Gran Premio de Australia de 2005 marcó el inicio de la temporada de Fórmula 1. La carrera tuvo lugar en el Melbourne Grand Prix Circuit el 6 de marzo. Fernando Alonso, al volante de su Renault, se aseguró la victoria después de una emocionante batalla en la pista. La competencia estuvo llena de acción y estrategias tácticas, lo que la convirtió en un evento inolvidable para los fanáticos de la Fórmula 1.', 2005, 'images/f1/2005.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Melbourne Grand Prix Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, BAR, Red Bull, Sauber, Jordan, Minardi', 'Australia', 58, '1. Alonso, 2. Fisichella, 3. Räikkönen', 'Alonso, Fisichella, Räikkönen, Schumacher, Barrichello, Montoya, Trulli, Webber, Button, Heidfeld, Coulthard, Klien, Villeneuve, Albers, Karthikeyan, Rosberg, Sato, Liuzzi, Massa, de la Rosa');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Malasia 2005', 'El Gran Premio de Malasia de 2005 fue la segunda carrera de la temporada de Fórmula 1 y se celebró en el impresionante Sepang International Circuit el 20 de marzo. Fernando Alonso nuevamente demostró su habilidad al volante y consiguió otra victoria para el equipo Renault. La carrera estuvo marcada por las cambiantes condiciones climáticas, lo que desafió a los pilotos y equipos a adaptarse rápidamente. La competencia estuvo llena de emoción y sorpresas, lo que la convirtió en un evento memorable para los aficionados de la Fórmula 1.', 2005, 'images/f1/2005.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Sepang International Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, BAR, Red Bull, Sauber, Jordan, Minardi', 'Malasia', 56, '1. Alonso, 2. Trulli, 3. Fisichella', 'Alonso, Trulli, Fisichella, Schumacher, Barrichello, Montoya, Webber, Coulthard, Button, Heidfeld, Villeneuve, Sato, Klien, Massa, Liuzzi, Rosberg, Karthikeyan, Albers, de la Rosa, Davidson');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahrein 2005', 'El Gran Premio de Bahrein de 2005 tuvo lugar en el Bahrain International Circuit el 3 de abril. La carrera fue la tercera de la temporada de Fórmula 1. Fernando Alonso continuó su dominio al conseguir otra victoria para el equipo Renault. La pista desafiante y el clima cálido añadieron un nivel adicional de dificultad, haciendo que la carrera fuera aún más emocionante para los competidores y los espectadores por igual. El Gran Premio de Bahrein de 2005 dejó una impresión duradera en la historia de la Fórmula 1 debido a su emocionante acción en la pista.', 2005, 'images/f1/2005.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Bahrain International Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, BAR, Red Bull, Sauber, Jordan, Minardi', 'Bahrein', 57, '1. Alonso, 2. Trulli, 3. Räikkönen', 'Alonso, Trulli, Räikkönen, Schumacher, Barrichello, Montoya, Webber, Coulthard, Button, Heidfeld, Villeneuve, Sato, Klien, Massa, Liuzzi, Rosberg, Karthikeyan, Albers, de la Rosa, Davidson');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP San Marino 2005', 'El Gran Premio de San Marino de 2005 se llevó a cabo en el Autodromo Enzo e Dino Ferrari el 24 de abril. Esta fue la cuarta carrera de la temporada de Fórmula 1. Fernando Alonso continuó su impresionante racha de victorias con otra brillante actuación para el equipo Renault. La pista desafiante y las estrategias tácticas hicieron que la carrera fuera emocionante de principio a fin. El Gran Premio de San Marino de 2005 dejó a los aficionados con momentos inolvidables y emociones intensas.', 2005, 'images/f1/2005.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Autodromo Enzo e Dino Ferrari', 'Renault, Ferrari, McLaren, Williams, Toyota, BAR, Red Bull, Sauber, Jordan, Minardi', 'San Marino', 62, '1. Alonso, 2. Schumacher, 3. Button', 'Alonso, Schumacher, Button, Trulli, Räikkönen, Montoya, Webber, Barrichello, Coulthard, Heidfeld, Massa, Villeneuve, Fisichella, Liuzzi, Karthikeyan, Albers, Monteiro, Sato, Klien, de la Rosa');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2005', 'El Gran Premio de España de 2005 se celebró en el Circuit de Barcelona-Catalunya el 8 de mayo. Kimi Räikkönen, al volante de su McLaren, se llevó la victoria en una carrera llena de acción y emociones. La competencia estuvo marcada por batallas intensas en la pista y estrategias tácticas entre los equipos principales. Alonso y Schumacher también ofrecieron una actuación memorable, luchando por los lugares del podio. La carrera fue un gran espectáculo para los aficionados, con momentos emocionantes que mantuvieron a todos al borde de sus asientos hasta la bandera a cuadros.', 2005, 'images/f1/2005.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Circuit de Barcelona-Catalunya', 'McLaren, Renault, Ferrari, Williams, Toyota, BAR, Red Bull, Sauber, Jordan, Minardi', 'España', 66, '1. Räikkönen, 2. Alonso, 3. Schumacher', 'Räikkönen, Alonso, Schumacher, Montoya, Webber, Barrichello, Coulthard, Button, Heidfeld, Villeneuve, Fisichella, Massa, Liuzzi, Karthikeyan, Albers, Monteiro, Sato, Klien, de la Rosa, Davidson');





-- 2006
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2006', 'El Gran Premio de Australia de 2006 marcó el inicio de una nueva temporada de Fórmula 1. La carrera se celebró en el Melbourne Grand Prix Circuit el 2 de abril. Fernando Alonso, al volante de su Renault, se alzó con la victoria tras una emocionante batalla en la pista. La competencia estuvo llena de acción desde la primera vuelta hasta la bandera a cuadros, manteniendo a los espectadores al borde de sus asientos.', 2006, 'images/f1/2006.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Melbourne Grand Prix Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, Honda, BMW Sauber, Red Bull, Midland, Toro Rosso', 'Australia', 58, '1. Alonso, 2. Webber, 3. Raikkonen', 'Alonso, Webber, Raikkonen, Fisichella, Button, Massa, Villeneuve, Trulli, R.Schumacher, Coulthard, Barrichello, Heidfeld, Montoya, Rosberg, Klien, Liuzzi, Albers, Speed, Yamamoto, M.Schumacher');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Malasia 2006', 'El Gran Premio de Malasia de 2006 se llevó a cabo en el Sepang International Circuit el 19 de marzo. Giancarlo Fisichella logró la victoria para el equipo Renault en una carrera desafiante. La intensa competencia y las condiciones climáticas cambiantes pusieron a prueba a los pilotos y equipos, haciendo que cada vuelta fuera emocionante.', 2006, 'images/f1/2006.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Sepang International Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, Honda, BMW Sauber, Red Bull, Midland, Toro Rosso', 'Malasia', 56, '1. Fisichella, 2. Alonso, 3. Trulli', 'Fisichella, Alonso, Trulli, Webber, Raikkonen, Button, Barrichello, Massa, Heidfeld, Rosberg, Coulthard, Villeneuve, Speed, Albers, Montoya, Klien, Liuzzi, M.Schumacher, Yamamoto, R.Schumacher');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahrein 2006', 'El Gran Premio de Bahrein de 2006 tuvo lugar en el Bahrain International Circuit el 12 de marzo. Fernando Alonso conduciendo para Renault ganó la carrera después de una impresionante actuación. La pista desafiante y las altas temperaturas añadieron un nivel adicional de dificultad, convirtiendo la competencia en un emocionante desafío.', 2006, 'images/f1/2006.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Bahrain International Circuit', 'Renault, Ferrari, McLaren, Williams, Toyota, Honda, BMW Sauber, Red Bull, Midland, Toro Rosso', 'Bahrein', 57, '1. Alonso, 2. Schumacher, 3. Raikkonen', 'Alonso, Schumacher, Raikkonen, Massa, Button, Fisichella, Trulli, Webber, Barrichello, Villeneuve, Coulthard, Rosberg, Monteiro, Speed, Liuzzi, Albers, Yamamoto, Klien, R.Schumacher, M.Schumacher');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2006', 'El Gran Premio de España de 2006 se celebró en el Circuit de Barcelona-Catalunya el 14 de mayo. Fernando Alonso, conduciendo para Renault, aseguró la victoria en casa tras una emocionante carrera. La pista exigente y las tácticas estratégicas hicieron que la competencia fuera intensa y emocionante para los pilotos y los espectadores.', 2006, 'images/f1/2006.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Circuit de Barcelona-Catalunya', 'Renault, Ferrari, McLaren, Williams, Toyota, Honda, BMW Sauber, Red Bull, Midland, Toro Rosso', 'España', 66, '1. Alonso, 2. Schumacher, 3. Raikkonen', 'Alonso, Schumacher, Raikkonen, Button, Fisichella, Barrichello, Massa, Webber, Rosberg, Coulthard, Trulli, Villeneuve, Monteiro, Speed, Liuzzi, Albers, Yamamoto, Klien, R.Schumacher, M.Schumacher');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Mónaco 2006', 'El Gran Premio de Mónaco de 2006 se llevó a cabo en el Circuit de Monaco el 28 de mayo. Fernando Alonso, al volante de su Renault, se adjudicó la victoria en una de las carreras más prestigiosas del calendario de la Fórmula 1. La carrera en las estrechas y sinuosas calles de Mónaco estuvo llena de drama y emoción, convirtiéndola en un evento inolvidable para pilotos y espectadores por igual. Alonso logró mantener su ventaja liderando desde la pole position hasta la línea de meta, pero la presión de Juan Pablo Montoya en McLaren mantuvo la emoción hasta el final. Kimi Raikkonen completó el podio después de una intensa batalla con los demás competidores. El Gran Premio de Mónaco de 2006 destacó por su espectacularidad y por las habilidades de conducción necesarias para dominar las difíciles condiciones del circuito urbano más famoso del mundo.', 2006, 'images/f1/2006.png', 'https://www.youtube.com/embed/zscZdvxOQ4A?si=19JozFQrKmGzoTW1', 'Circuit de Monaco', 'Renault, Ferrari, McLaren, Williams, Toyota, Honda, BMW Sauber, Red Bull, Midland, Toro Rosso', 'Mónaco', 78, '1. Alonso, 2. Montoya, 3. Raikkonen', 'Alonso, Montoya, Raikkonen, Button, Massa, Barrichello, Webber, Rosberg, Trulli, Villeneuve, Fisichella, Coulthard, Monteiro, Speed, Liuzzi, Albers, Yamamoto, Klien, R.Schumacher, M.Schumacher');


-- 2007
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2007', 'El Gran Premio de Australia de 2007 se llevó a cabo en el Melbourne Grand Prix Circuit el 18 de marzo. Kimi Räikkönen, al volante de su Ferrari, cruzó la línea de meta en primer lugar después de una emocionante carrera. La competencia estuvo llena de acción desde el principio hasta el final, con Räikkönen, Alonso y Hamilton luchando por el liderazgo en varias ocasiones. El Gran Premio de Australia marcó el comienzo de una temporada emocionante y prometedora.', 2007, 'images/f1/2007.png', 'https://www.youtube.com/embed/L4ceBUOAU_w?si=dFlHKdgGF-OacHGP', 'Melbourne Grand Prix Circuit', 'Ferrari, McLaren, BMW Sauber, Renault, Williams, Red Bull, Toyota, Honda, Super Aguri, Toro Rosso', 'Australia', 58, '1. Raikkonen, 2. Alonso, 3. Hamilton', 'Raikkonen, Alonso, Hamilton, Heidfeld, Kubica, Fisichella, Massa, Rosberg, Coulthard, Webber, Trulli, Button, Barrichello, Sato, Davidson, Wurz, Speed, Liuzzi, Albers, Sutil');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Malasia 2007', 'El Gran Premio de Malasia de 2007 se celebró en el Sepang International Circuit el 8 de abril. Fernando Alonso, al volante de su McLaren, triunfó en una carrera desafiante bajo las condiciones cambiantes del clima. La lluvia intermitente añadió un elemento impredecible, haciendo que la estrategia fuera crucial para el éxito. Alonso demostró su habilidad y determinación al mantenerse en la delantera y asegurar la victoria para su equipo.', 2007, 'images/f1/2007.png', 'https://www.youtube.com/embed/L4ceBUOAU_w?si=dFlHKdgGF-OacHGP', 'Sepang International Circuit', 'Ferrari, McLaren, BMW Sauber, Renault, Williams, Red Bull, Toyota, Honda, Super Aguri, Toro Rosso', 'Malasia', 56, '1. Alonso, 2. Massa, 3. Hamilton', 'Alonso, Massa, Hamilton, Heidfeld, Fisichella, Kubica, Rosberg, Button, Webber, Coulthard, Trulli, Wurz, Barrichello, Sato, Davidson, Liuzzi, Speed, Albers, Sutil, Yamamoto');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahrein 2007', 'El Gran Premio de Bahrein de 2007 tuvo lugar en el Bahrain International Circuit el 15 de abril. Felipe Massa, conduciendo para Ferrari, se alzó con la victoria en una carrera emocionante. El calor extremo y las condiciones desafiantes de la pista hicieron que la competencia fuera aún más intensa. Massa demostró su habilidad al mantenerse en la delantera y asegurar una victoria crucial para su equipo en las primeras etapas del campeonato.', 2007, 'images/f1/2007.png', 'https://www.youtube.com/embed/L4ceBUOAU_w?si=dFlHKdgGF-OacHGP', 'Bahrain International Circuit', 'Ferrari, McLaren, BMW Sauber, Renault, Williams, Red Bull, Toyota, Honda, Super Aguri, Toro Rosso', 'Bahrein', 57, '1. Massa, 2. Hamilton, 3. Raikkonen', 'Massa, Hamilton, Raikkonen, Alonso, Kubica, Heidfeld, Coulthard, Rosberg, Webber, Button, Fisichella, Liuzzi, Trulli, Sato, Barrichello, Davidson, Speed, Albers, Wurz, Sutil');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2007', 'El Gran Premio de España de 2007 se celebró en el Circuit de Barcelona-Catalunya el 13 de mayo. Felipe Massa, al volante de su Ferrari, logró la victoria en una carrera emocionante. El circuito exigente y las estrategias tácticas mantuvieron la competencia cerrada hasta la bandera a cuadros. Massa demostró su habilidad y resistencia al liderar desde la pole position hasta la victoria.', 2007, 'images/f1/2007.png', 'https://www.youtube.com/embed/L4ceBUOAU_w?si=dFlHKdgGF-OacHGP', 'Circuit de Barcelona-Catalunya', 'Ferrari, McLaren, BMW Sauber, Renault, Williams, Red Bull, Toyota, Honda, Super Aguri, Toro Rosso', 'España', 66, '1. Massa, 2. Alonso, 3. Hamilton', 'Massa, Alonso, Hamilton, Raikkonen, Heidfeld, Kubica, Fisichella, Trulli, Webber, Coulthard, Rosberg, Button, Barrichello, Sato, Davidson, Speed, Albers, Wurz, Sutil, Yamamoto');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Mónaco 2007', 'El Gran Premio de Mónaco de 2007 se llevó a cabo en el Circuit de Monaco el 27 de mayo. Fernando Alonso, al volante de su McLaren, ganó en una carrera emocionante que destacó por su drama y tensión. La pista estrecha y sinuosa de Mónaco presentó desafíos únicos para los pilotos, y Alonso demostró su maestría al mantenerse en la delantera y asegurar la victoria en una de las carreras más prestigiosas del calendario de la Fórmula 1. La carrera estuvo marcada por la presión constante sobre Alonso por parte de Lewis Hamilton, su compañero de equipo en McLaren, quien lo siguió de cerca durante gran parte de la carrera. Sin embargo, Alonso resistió la presión y cruzó la línea de meta en primer lugar, asegurando una victoria crucial para su equipo.', 2007, 'images/f1/2007.png', 'https://www.youtube.com/embed/L4ceBUOAU_w?si=dFlHKdgGF-OacHGP', 'Circuit de Monaco', 'Ferrari, McLaren, BMW Sauber, Renault, Williams, Red Bull, Toyota, Honda, Super Aguri, Toro Rosso', 'Mónaco', 78, '1. Alonso, 2. Hamilton, 3. Heidfeld', 'Alonso, Hamilton, Heidfeld, Massa, Kubica, Fisichella, Coulthard, Webber, Trulli, Rosberg, Button, Sato, Davidson, Wurz, Barrichello, Liuzzi, Speed, Albers, Sutil, Yamamoto');


-- 2010
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahrein 2010', 'El Gran Premio de Bahrein de 2010 fue la primera carrera de la temporada y se celebró en el Bahrain International Circuit el 14 de marzo. Fernando Alonso, conduciendo para Ferrari, ganó una emocionante carrera bajo el calor del desierto. Fue una victoria memorable para Alonso, que demostró su destreza tanto en la clasificación como en la carrera principal.', 2010, 'images/f1/2010.png', 'https://www.youtube.com/embed/LwxInKB6uu0?si=jFOfiWsP5FlrnUfW', 'Bahrain International Circuit', 'Ferrari, McLaren, Mercedes, Red Bull, Renault, Williams, Force India, Toro Rosso, Lotus, HRT', 'Bahrein', 57, '1. Alonso, 2. Massa, 3. Hamilton', 'Alonso, Massa, Hamilton, Vettel, Rosberg, Schumacher, Webber, Button, Kubica, Liuzzi, Sutil, Buemi, Alguersuari, Barrichello, Hulkenberg, Petrov, Kovalainen, Trulli, Glock, Senna');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2010', 'El Gran Premio de Australia de 2010 tuvo lugar en el Melbourne Grand Prix Circuit el 28 de marzo. Jenson Button, al volante de su McLaren, logró una victoria sorprendente en una carrera caótica marcada por múltiples incidentes y cambios climáticos. Fue una demostración de habilidad y determinación por parte de Button, que navegó hábilmente a través de las difíciles condiciones para asegurar la victoria.', 2010, 'images/f1/2010.png', 'https://www.youtube.com/embed/LwxInKB6uu0?si=jFOfiWsP5FlrnUfW', 'Melbourne Grand Prix Circuit', 'McLaren, Ferrari, Mercedes, Red Bull, Renault, Williams, Force India, Toro Rosso, Lotus, HRT', 'Australia', 58, '1. Button, 2. Kubica, 3. Massa', 'Button, Kubica, Massa, Alonso, Vettel, Rosberg, Hamilton, Webber, Schumacher, Sutil, Liuzzi, Petrov, Hulkenberg, Barrichello, Alguersuari, Buemi, Trulli, Kovalainen, Glock, Chandhok');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Malasia 2010', 'El Gran Premio de Malasia de 2010 se llevó a cabo en el Sepang International Circuit el 4 de abril. Sebastian Vettel, al volante de su Red Bull, dominó la carrera desde el inicio, superando las condiciones climáticas cambiantes y los desafíos en pista para lograr una victoria impresionante. Fue una actuación magistral de Vettel, que demostró su habilidad en todas las condiciones.', 2010, 'images/f1/2010.png', 'https://www.youtube.com/embed/LwxInKB6uu0?si=jFOfiWsP5FlrnUfW', 'Sepang International Circuit', 'Red Bull, McLaren, Ferrari, Mercedes, Renault, Williams, Force India, Toro Rosso, Lotus, HRT', 'Malasia', 56, '1. Vettel, 2. Webber, 3. Rosberg', 'Vettel, Webber, Rosberg, Kubica, Sutil, Massa, Hamilton, Alonso, Schumacher, Button, Petrov, Hulkenberg, Alguersuari, Liuzzi, Barrichello, Buemi, Kobayashi, Trulli, Kovalainen, Senna');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP China 2010', 'El Gran Premio de China de 2010 se llevó a cabo en el Shanghai International Circuit el 18 de abril. Jenson Button, al volante de su McLaren, logró una emocionante victoria en una carrera marcada por las condiciones climáticas cambiantes y la estrategia en boxes. Fue una actuación impresionante de Button, que demostró su habilidad para adaptarse a las condiciones y superar a sus rivales.', 2010, 'images/f1/2010.png', 'https://www.youtube.com/embed/LwxInKB6uu0?si=jFOfiWsP5FlrnUfW', 'Shanghai International Circuit', 'McLaren, Ferrari, Mercedes, Red Bull, Renault, Williams, Force India, Toro Rosso, Lotus, HRT', 'China', 56, '1. Button, 2. Hamilton, 3. Rosberg', 'Button, Hamilton, Rosberg, Webber, Vettel, Schumacher, Kubica, Liuzzi, Barrichello, Alonso, Sutil, Massa, Petrov, Buemi, Alguersuari, Hulkenberg, Kobayashi, Trulli, Kovalainen, di Grassi');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2010', 'El Gran Premio de España de 2010 tuvo lugar en el Circuit de Barcelona-Catalunya el 9 de mayo. Mark Webber, al volante de su Red Bull, logró una victoria dominante en una carrera que estuvo marcada por el ritmo implacable del australiano. Fue una actuación impresionante de Webber, que demostró su habilidad para controlar la carrera desde la pole position hasta la bandera a cuadros.', 2010, 'images/f1/2010.png', 'https://www.youtube.com/embed/LwxInKB6uu0?si=jFOfiWsP5FlrnUfW', 'Circuit de Barcelona-Catalunya', 'Red Bull, McLaren, Ferrari, Mercedes, Renault, Williams, Force India, Toro Rosso, Lotus, HRT', 'España', 66, '1. Webber, 2. Alonso, 3. Vettel', 'Webber, Alonso, Vettel, Hamilton, Button, Schumacher, Rosberg, Massa, Sutil, Liuzzi, Petrov, Kubica, Buemi, Alguersuari, Hulkenberg, Barrichello, Kobayashi, Kovalainen, Trulli, di Grassi');


-- 2012
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2012', 'El Gran Premio de Australia de 2012 tuvo lugar en el Melbourne Grand Prix Circuit. Jenson Button de McLaren logró una victoria emocionante en una carrera marcada por condiciones climáticas impredecibles y múltiples incidentes en pista. Button demostró un manejo magistral y estrategia inteligente para asegurar la victoria.', 2012, 'images/f1/2012.png', 'https://www.youtube.com/embed/bYdwXDUuPtU?si=omdIxptYmRxM1eaJ', 'Melbourne Grand Prix Circuit', 'Red Bull, McLaren, Ferrari, Mercedes, Lotus, Force India, Sauber, Toro Rosso, Williams, Caterham', 'Australia', 58, '1. Button, 2. Vettel, 3. Hamilton', 'Button, Vettel, Hamilton, Webber, Alonso, Kobayashi, Raikkonen, Perez, Ricciardo, Vergne, Schumacher, Rosberg, Di Resta, Maldonado, Senna, Kovalainen, Petrov, Glock, Pic, Karthikeyan');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Malasia 2012', 'El Gran Premio de Malasia de 2012 se llevó a cabo en el Sepang International Circuit. Fernando Alonso de Ferrari logró una victoria sorprendente en una carrera marcada por condiciones climáticas extremadamente difíciles. Alonso mostró su habilidad para adaptarse a las cambiantes condiciones de la pista y aseguró una victoria impresionante.', 2012, 'images/f1/2012.png', 'https://www.youtube.com/embed/bYdwXDUuPtU?si=omdIxptYmRxM1eaJ', 'Sepang International Circuit', 'Red Bull, McLaren, Ferrari, Mercedes, Lotus, Force India, Sauber, Toro Rosso, Williams, Caterham', 'Malasia', 56, '1. Alonso, 2. Perez, 3. Hamilton', 'Alonso, Perez, Hamilton, Webber, Raikkonen, Grosjean, Senna, Kobayashi, Schumacher, Vergne, Button, Hulkenberg, Maldonado, Di Resta, Ricciardo, Kovalainen, Petrov, Pic, Glock, Karthikeyan');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP China 2012', 'El Gran Premio de China de 2012 se llevó a cabo en el Shanghai International Circuit. Nico Rosberg de Mercedes logró una victoria impresionante en una carrera llena de acción y estrategias emocionantes. Rosberg demostró su habilidad para mantener el control y superar a sus rivales en condiciones difíciles.', 2012, 'images/f1/2012.png', 'https://www.youtube.com/embed/bYdwXDUuPtU?si=omdIxptYmRxM1eaJ', 'Shanghai International Circuit', 'Red Bull, McLaren, Ferrari, Mercedes, Lotus, Force India, Sauber, Toro Rosso, Williams, Caterham', 'China', 56, '1. Rosberg, 2. Button, 3. Hamilton', 'Rosberg, Button, Hamilton, Webber, Alonso, Vettel, Rosberg, Raikkonen, Kobayashi, Grosjean, Senna, Perez, Maldonado, Di Resta, Vergne, Hulkenberg, Ricciardo, Kovalainen, Petrov, Pic');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahréin 2012', 'El Gran Premio de Bahréin de 2012 se llevó a cabo en el Bahrain International Circuit. Sebastian Vettel de Red Bull logró una victoria dominante en una carrera que estuvo marcada por la tensión política y social en el país anfitrión. Vettel demostró su habilidad para mantener la calma bajo presión y asegurar la victoria para su equipo.', 2012, 'images/f1/2012.png', 'https://www.youtube.com/embed/bYdwXDUuPtU?si=omdIxptYmRxM1eaJ', 'Bahrain International Circuit', 'Red Bull, McLaren, Ferrari, Mercedes, Lotus, Force India, Sauber, Toro Rosso, Williams, Caterham', 'Bahréin', 57, '1. Vettel, 2. Raikkonen, 3. Grosjean', 'Vettel, Raikkonen, Grosjean, Rosberg, Hamilton, Webber, Alonso, Perez, Button, Kobayashi, Schumacher, Maldonado, Di Resta, Senna, Ricciardo, Vergne, Petrov, Kovalainen, Glock, Pic');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2012', 'El Gran Premio de España de 2012 tuvo lugar en el Circuit de Barcelona-Catalunya. Pastor Maldonado de Williams logró una victoria sorprendente en una carrera llena de emoción y drama. Maldonado mostró un manejo magistral y determinación para superar a los favoritos y asegurar una victoria inesperada para su equipo.', 2012, 'images/f1/2012.png', 'https://www.youtube.com/embed/bYdwXDUuPtU?si=omdIxptYmRxM1eaJ', 'Circuit de Barcelona-Catalunya', 'Red Bull, McLaren, Ferrari, Mercedes, Lotus, Force India, Sauber, Toro Rosso, Williams, Caterham', 'España', 66, '1. Maldonado, 2. Alonso, 3. Raikkonen', 'Maldonado, Alonso, Raikkonen, Grosjean, Hamilton, Vettel, Webber, Kobayashi, Button, Perez, Rosberg, Di Resta, Senna, Vergne, Ricciardo, Hulkenberg, Petrov, Kovalainen, Glock, Pic');


-- 2023
INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Australia 2023', 'El Gran Premio de Australia de 2023 se llevó a cabo en el Melbourne Grand Prix Circuit. Max Verstappen, compitiendo para Red Bull Racing, logró una emocionante victoria en la carrera de apertura de la temporada. Verstappen demostró su habilidad para dominar la pista y asegurar una victoria crucial para su equipo.', 2023, 'images/f1/2023.png', 'https://www.youtube.com/embed/eGDOeMCViCo?si=dGZAypqVVBl6uG-X', 'Melbourne Grand Prix Circuit', 'Mercedes, Red Bull Racing, Ferrari, Alpine, Aston Martin, Alfa Romeo, Haas, Williams, AlphaTauri', 'Australia', 58, '1. Verstappen, 2. Hamilton, 3. Bottas', 'Verstappen, Hamilton, Bottas, Perez, Leclerc, Ocon, Sainz, Norris, Ricciardo, Russell, Stroll, Gasly, Alonso, Tsunoda, Giovinazzi, Zhou, Latifi, Schumacher, Mazepin, Armstrong');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Arabia Saudita 2023', 'El Gran Premio de Arabia Saudita de 2023 se llevó a cabo en el Circuito Jeddah Street Circuit. Lewis Hamilton, de Mercedes, logró una victoria impresionante en un emocionante Gran Premio nocturno. Hamilton demostró su habilidad para mantener la calma bajo presión y asegurar una victoria crucial en el campeonato.', 2023, 'images/f1/2023.png', 'https://www.youtube.com/embed/eGDOeMCViCo?si=dGZAypqVVBl6uG-X', 'Circuito Jeddah Street Circuit', 'Mercedes, Red Bull Racing, Ferrari, Alpine, Aston Martin, Alfa Romeo, Haas, Williams, AlphaTauri', 'Arabia Saudita', 50, '1. Hamilton, 2. Verstappen, 3. Bottas', 'Hamilton, Verstappen, Bottas, Perez, Leclerc, Sainz, Ocon, Norris, Ricciardo, Russell, Stroll, Gasly, Alonso, Tsunoda, Giovinazzi, Zhou, Latifi, Schumacher, Mazepin, Armstrong');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Bahréin 2023', 'El Gran Premio de Bahréin de 2023 se llevó a cabo en el Bahrain International Circuit. Charles Leclerc, de Ferrari, logró una emocionante victoria bajo luces brillantes en el circuito de Sakhir. Leclerc demostró su habilidad para administrar neumáticos y estrategias para asegurar la victoria.', 2023, 'images/f1/2023.png', 'https://www.youtube.com/embed/eGDOeMCViCo?si=dGZAypqVVBl6uG-X', 'Bahrain International Circuit', 'Mercedes, Red Bull Racing, Ferrari, Alpine, Aston Martin, Alfa Romeo, Haas, Williams, AlphaTauri', 'Bahréin', 57, '1. Leclerc, 2. Hamilton, 3. Norris', 'Leclerc, Hamilton, Norris, Bottas, Verstappen, Perez, Sainz, Ocon, Ricciardo, Russell, Alonso, Gasly, Stroll, Tsunoda, Giovinazzi, Zhou, Latifi, Schumacher, Mazepin, Armstrong');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP España 2023', 'El Gran Premio de España de 2023 tuvo lugar en el Circuit de Barcelona-Catalunya. Max Verstappen, de Red Bull Racing, aseguró una victoria dominante en una emocionante carrera en el circuito español. Verstappen demostró su habilidad para superar a sus rivales y consolidar su posición en la cima del campeonato.', 2023, 'images/f1/2023.png', 'https://www.youtube.com/embed/eGDOeMCViCo?si=dGZAypqVVBl6uG-X', 'Circuit de Barcelona-Catalunya', 'Mercedes, Red Bull Racing, Ferrari, Alpine, Aston Martin, Alfa Romeo, Haas, Williams, AlphaTauri', 'España', 66, '1. Verstappen, 2. Hamilton, 3. Bottas', 'Verstappen, Hamilton, Bottas, Leclerc, Norris, Sainz, Perez, Ocon, Ricciardo, Russell, Alonso, Gasly, Stroll, Tsunoda, Giovinazzi, Zhou, Latifi, Schumacher, Mazepin, Armstrong');

INSERT INTO F1Content (nombre_contenido, descripcion, anho, url_image, url_video, circuito, equipos, nacionalidad, duracion, otros_datos, pilotos)
VALUES ('GP Mónaco 2023', 'El Gran Premio de Mónaco de 2023 se llevó a cabo en el Circuit de Monaco. Lewis Hamilton, de Mercedes, aseguró una impresionante victoria en las estrechas calles de Mónaco. Hamilton demostró su maestría en el circuito urbano más famoso del mundo y aseguró una victoria crucial en el campeonato.', 2023, 'images/f1/2023.png', 'https://www.youtube.com/embed/eGDOeMCViCo?si=dGZAypqVVBl6uG-X', 'Circuit de Monaco', 'Mercedes, Red Bull Racing, Ferrari, Alpine, Aston Martin, Alfa Romeo, Haas, Williams, AlphaTauri', 'Mónaco', 78, '1. Hamilton, 2. Verstappen, 3. Bottas', 'Hamilton, Verstappen, Bottas, Leclerc, Norris, Perez, Ocon, Sainz, Ricciardo, Russell, Alonso, Gasly, Stroll, Tsunoda, Giovinazzi, Zhou, Latifi, Schumacher, Mazepin, Armstrong');


-- Football Content
-- Liga Española 2024
-- Partido 1
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Barcelona vs Real Madrid 2024', 'El Clásico español entre Barcelona y Real Madrid siempre es un evento imperdible. En este enfrentamiento, dos de los equipos más poderosos de La Liga se enfrentan en una batalla por la supremacía. ¿Quién saldrá victorioso esta vez?', 2024, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/iS6dII37CwM?si=v87ogWEmKufv4sah', 'Camp Nou', 'Barcelona, Real Madrid', 'Liga Española', '90', 'Partido jugado el 26 de marzo de 2024', 'Lionel Messi, Antoine Griezmann, Karim Benzema, Vinícius Júnior, Luka Modrić');

-- Partido 2
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Atlético de Madrid vs Sevilla 2024', 'Un emocionante enfrentamiento entre el Atlético de Madrid y el Sevilla promete un choque de estilos. Con ambos equipos luchando por el título, cada gol y cada jugada serán cruciales en este partido de alto vuelo.', 2024, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/wCHO-uNB3TI?si=ZXEIuczq4jm09wkh', 'Wanda Metropolitano', 'Atlético de Madrid, Sevilla', 'Liga Española', '90', 'Partido jugado el 27 de marzo de 2024', 'Luis Suárez, João Félix, Youssef En-Nesyri, Jesús Navas, Ivan Rakitić');

-- Partido 3
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Sociedad vs Valencia 2024', 'La Real Sociedad se enfrenta al Valencia en un duelo que promete ser vibrante. Con ambos equipos buscando asegurar un lugar en competiciones europeas, cada momento será crucial en este encuentro lleno de acción.', 2024, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/CmZ9tsw743g?si=r-BqZlwTIhGFNnLO', 'Reale Arena', 'Real Sociedad, Valencia', 'Liga Española', '90', 'Partido jugado el 28 de marzo de 2024', 'Mikel Oyarzabal, Alexander Isak, Carlos Soler, Gonçalo Guedes, José Gayà');

-- Partido 4
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Villarreal vs Athletic Club 2024', 'El Villarreal se enfrenta al Athletic Club en un duelo de contrastes. Con el Villarreal buscando consolidarse en la parte alta de la tabla y el Athletic luchando por mantenerse en la liga, este partido promete ser una batalla intensa.', 2024, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/iXEpZoEc1cA?si=wRqBYeoJA7y6x937', 'Estadio de la Cerámica', 'Villarreal, Athletic Club', 'Liga Española', '90', 'Partido jugado el 29 de marzo de 2024', 'Gerard Moreno, Paco Alcácer, Iñaki Williams, Raúl García, Unai Simón');

-- Partido 5
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Betis vs Getafe 2024', 'El Betis se enfrenta al Getafe en un choque de mitad de tabla. Con ambos equipos buscando mejorar su posición en la clasificación, cada punto será vital en este emocionante encuentro.', 2024, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/NKKEkCGQQmQ?si=kZ_lWVMnHO7d6iRA', 'Estadio Benito Villamarín', 'Betis, Getafe', 'Liga Española', '90', 'Partido jugado el 30 de marzo de 2024', 'Nabil Fekir, Sergio Canales, Jaime Mata, Marc Cucurella, Enes Ünal');


-- Liga Española 2023
-- Partido 1
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Sevilla vs Real Betis 2023', 'El derbi sevillano entre Sevilla y Real Betis es uno de los enfrentamientos más intensos de La Liga. Ambos equipos luchan por el dominio de la ciudad y por los puntos en la tabla de clasificación.', 2023, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/Ri9XFLoifQg?si=COEjfeQMfAtORBDJ', 'Estadio Ramón Sánchez-Pizjuán', 'Sevilla, Real Betis', 'Liga Española', '90', 'Partido jugado en 2023', 'Lucas Ocampos, Éver Banega, Nabil Fekir, Borja Iglesias');

-- Partido 2
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Atlético 2023', 'El derbi madrileño entre Real Madrid y Atlético de Madrid es siempre un enfrentamiento emocionante. Dos de los equipos más grandes de España se disputan la supremacía de la capital.', 2023, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/cHPe6lITeTA?si=ihDkcWxcehB6Gtva', 'Santiago Bernabéu', 'Real Madrid, Atlético de Madrid', 'Liga Española', '90', 'Partido jugado en 2023', 'Karim Benzema, Toni Kroos, Luis Suárez, João Félix');

-- Partido 3
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Barcelona vs Valencia 2023', 'Un encuentro entre dos equipos con una gran historia en La Liga. Barcelona y Valencia se enfrentan en un partido que promete ser emocionante y lleno de acción.', 2023, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/mXQ48fRRX34?si=sRomJPACe58xFCRP', 'Camp Nou', 'Barcelona, Valencia', 'Liga Española', '90', 'Partido jugado en 2023', 'Lionel Messi, Ansu Fati, Gonçalo Guedes, José Gayà');

-- Partido 4
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Villarreal vs Real Sociedad 2023', 'Dos equipos con estilos de juego únicos se enfrentan en un emocionante duelo en La Liga. Villarreal y Real Sociedad buscarán la victoria en este partido crucial.', 2023, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/RoH3wvZIYRk?si=3vsgaESMGdRbaCVP', 'Estadio de la Cerámica', 'Villarreal, Real Sociedad', 'Liga Española', '90', 'Partido jugado en 2023', 'Gerard Moreno, Carlos Bacca, Mikel Oyarzabal, David Silva');

-- Partido 5
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Athletic Club vs Eibar 2023', 'Dos equipos del norte de España se enfrentan en un duelo que puede influir en la lucha por la permanencia en La Liga. Athletic Club y Eibar buscarán los tres puntos en este emocionante partido.', 2023, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/vjvDeL6nZUo?si=kSCn2QAJbsiFfJyv', 'San Mamés', 'Athletic Club, Eibar', 'Liga Española', '90', 'Partido jugado en 2023', 'Iñaki Williams, Raúl García, Kike García, Sergi Enrich');


-- Partido 1 (2022)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Barcelona 2022', 'El clásico español entre Real Madrid y Barcelona es uno de los enfrentamientos más emocionantes del mundo del fútbol. En este partido, dos gigantes se enfrentan por el honor y los puntos en la Liga Española.', 2022, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/swLI6zuXtp4?si=f3G1Qa1nhcxo9VsZ', 'Santiago Bernabéu', 'Real Madrid, Barcelona', 'Liga Española', '90', 'Partido jugado en 2022', 'Karim Benzema, Vinícius Júnior, Lionel Messi, Frenkie de Jong');

-- Partido 2 (2022)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Atlético de Madrid vs Sevilla 2022', 'El Atlético de Madrid recibe al Sevilla en un enfrentamiento crucial por la parte alta de la tabla. Ambos equipos buscan asegurar su posición en la lucha por el título de La Liga.', 2022, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/1dxh7Rlij50?si=yU8GCE-F9ibbM_Hy', 'Wanda Metropolitano', 'Atlético de Madrid, Sevilla', 'Liga Española', '90', 'Partido jugado en 2022', 'Luis Suárez, Marcos Acuña, Youssef En-Nesyri, Jesús Navas');

-- Partido 3 (2022)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Valencia vs Real Sociedad 2022', 'Valencia se enfrenta a la Real Sociedad en un partido lleno de expectativas. Ambos equipos buscarán los tres puntos para consolidar sus respectivas posiciones en la clasificación.', 2022, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/IRxVUQMQo-k?si=4HpDkjwWeiicmXlM', 'Estadio Mestalla', 'Valencia, Real Sociedad', 'Liga Española', '90', 'Partido jugado en 2022', 'Gonçalo Guedes, Carlos Soler, Mikel Oyarzabal, Alexander Isak');

-- Partido 4 (2022)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Villarreal vs Athletic Club 2022', 'Villarreal y Athletic Club se enfrentan en un partido que promete emociones fuertes. Ambos equipos tienen una fuerte historia en La Liga y buscan agregar otro capítulo memorable.', 2022, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/9nSsd7MBJx4?si=mlXlY0TyWrQJLcvD', 'Estadio de la Cerámica', 'Villarreal, Athletic Club', 'Liga Española', '90', 'Partido jugado en 2022', 'Gerard Moreno, Paco Alcácer, Iñaki Williams, Raúl García');

-- Partido 5 (2022)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Sevilla vs Real Betis 2022', 'El derbi sevillano entre Sevilla y Real Betis es un enfrentamiento lleno de pasión y rivalidad. Ambos equipos darán lo mejor de sí en busca de los derechos de fanfarronear en la ciudad.', 2022, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/df2HS0-mk5c?si=w1eGxlyWjIta4I9N', 'Estadio Ramón Sánchez-Pizjuán', 'Sevilla, Real Betis', 'Liga Española', '90', 'Partido jugado en 2022', 'Lucas Ocampos, Éver Banega, Nabil Fekir, Borja Iglesias');



-- Partido 1 (2021)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Barcelona vs Real Madrid 2021', 'El Clásico entre Barcelona y Real Madrid es el partido más destacado de La Liga. La rivalidad entre estos dos gigantes del fútbol mundial siempre garantiza un espectáculo emocionante.', 2021, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/TU6zM63GuLo?si=mMVx74DPqacwFEIt', 'Camp Nou', 'Barcelona, Real Madrid', 'Liga Española', '90', 'Partido jugado en 2021', 'Lionel Messi, Karim Benzema, Sergio Ramos, Ansu Fati');

-- Partido 2 (2021)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Atlético de Madrid vs Sevilla 2021', 'Atlético de Madrid recibe a Sevilla en un duelo crucial por los puestos de arriba en La Liga. Ambos equipos buscarán la victoria para mantener sus aspiraciones de título.', 2021, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/FqBQT7GIxoI?si=vXWuOC3-oBnKCS1c', 'Wanda Metropolitano', 'Atlético de Madrid, Sevilla', 'Liga Española', '90', 'Partido jugado en 2021', 'Luis Suárez, João Félix, Youssef En-Nesyri, Jesús Navas');

-- Partido 3 (2021)A
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Sociedad vs Villarreal 2021', 'Real Sociedad y Villarreal se enfrentan en un partido crucial en la lucha por los puestos europeos. Ambos equipos buscan la victoria para consolidarse en la parte alta de la tabla.', 2021, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/4Uzp8HAwMEM?si=cgkXbMZ979y02J6w', 'Estadio Anoeta', 'Real Sociedad, Villarreal', 'Liga Española', '90', 'Partido jugado en 2021', 'Mikel Oyarzabal, Alexander Isak, Gerard Moreno, Dani Parejo');
-- Partido 4 (2021)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Sevilla 2021', 'Real Madrid y Sevilla se enfrentan en un choque entre dos equipos de élite de La Liga. Ambos buscarán los tres puntos para mantener sus respectivas luchas en la tabla.', 2021, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/_28CyM8Ndio?si=q0odw-WzaYFNBxvA', 'Santiago Bernabéu', 'Real Madrid, Sevilla', 'Liga Española', '90', 'Partido jugado en 2021', 'Karim Benzema, Vinícius Júnior, Youssef En-Nesyri, Jesús Navas');

-- Partido 5 (2021)
INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Barcelona vs Atlético de Madrid 2021', 'Barcelona y Atlético de Madrid se enfrentan en un partido clave en la carrera por el título de La Liga. Este enfrentamiento promete ser un espectáculo emocionante de principio a fin.', 2021, 'images/FootballContent/LALIGA.jpg', 'https://www.youtube.com/embed/CryjvegXMcI?si=Vhoxd2jHRc3Sjnwj', 'Camp Nou', 'Barcelona, Atlético de Madrid', 'Liga Española', '90', 'Partido jugado en 2021', 'Lionel Messi, Luis Suárez, Antoine Griezmann, João Félix');


-- Champions

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Juventus 2017', 'La final de la Champions League 2017 enfrentó al Real Madrid contra la Juventus. Fue un partido emocionante que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Millennium Stadium', 'Real Madrid, Juventus', 'Champions League', '90', 'Final de la Champions League 2017', 'Cristiano Ronaldo, Sergio Ramos, Paulo Dybala, Gianluigi Buffon');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs. Atlético 2017', 'El Real Madrid se enfrentó al Atlético de Madrid en las semifinales de la Champions League 2017. Fue un enfrentamiento emocionante que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Santiago Bernabéu', 'Real Madrid, Atlético de Madrid', 'Champions League', '90', 'Semifinal de la Champions League 2017', 'Cristiano Ronaldo, Antoine Griezmann, Karim Benzema, Jan Oblak');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Bayern 2017', 'El Real Madrid se enfrentó al Bayern de Múnich en los cuartos de final de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Santiago Bernabéu', 'Real Madrid, Bayern de Múnich', 'Champions League', '90', 'Cuartos de final de la Champions League 2017', 'Cristiano Ronaldo, Robert Lewandowski, Gareth Bale, Manuel Neuer');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Nápoles 2017', 'El Real Madrid se enfrentó al Nápoles en los octavos de final de la Champions League 2017. Fue un enfrentamiento emocionante que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Santiago Bernabéu', 'Real Madrid, Nápoles', 'Champions League', '90', 'Octavos de final de la Champions League 2017', 'Cristiano Ronaldo, Lorenzo Insigne, Karim Benzema, Pepe Reina');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Dortmund 2017', 'El Real Madrid se enfrentó al Borussia Dortmund en la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Signal Iduna Park', 'Real Madrid, Borussia Dortmund', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 6/6', 'Cristiano Ronaldo, Pierre-Emerick Aubameyang, Karim Benzema, Roman Bürki');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Sporting vs Real Madrid 2017', 'El Sporting de Lisboa se enfrentó al Real Madrid en la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estádio José Alvalade', 'Sporting de Lisboa, Real Madrid', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 5/6', 'Gelson Martins, Cristiano Ronaldo, Karim Benzema, Rui Patrício');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Varsovia vs. Real Madrid 2017', 'El Legia de Varsovia se enfrentó al Real Madrid en la jornada 2 de la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Wojska Polskiego', 'Legia de Varsovia, Real Madrid', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 4/6', 'Vadis Odjidja-Ofoe, Gareth Bale, Marco Asensio, Keylor Navas');


INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Varsovia 2017', 'El Real Madrid se enfrentó al Legia de Varsovia en la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Santiago Bernabéu', 'Real Madrid, Legia de Varsovia', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 3/6', 'Cristiano Ronaldo, Gareth Bale, Vadis Odjidja-Ofoe, Keylor Navas');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Dortmund vs Real Madrid 2017', 'El Borussia Dortmund se enfrentó al Real Madrid en la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Signal Iduna Park', 'Borussia Dortmund, Real Madrid', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 2/6', 'Pierre-Emerick Aubameyang, Cristiano Ronaldo, Karim Benzema, Roman Bürki');

INSERT INTO Football_Content (nombre_contenido, descripcion, anho, url_image, url_video, estadio, equipos, competicion, duracion, otros_datos, jugadores)
VALUES ('Real Madrid vs Sporting 2017', 'El Real Madrid se enfrentó al Sporting de Lisboa en la jornada 1 de la fase de grupos de la Champions League 2017. Fue un emocionante encuentro que terminó con la victoria del Real Madrid.', 2017, 'images/FootballContent/Champions.jpg', 'https://www.youtube.com/embed/OnAkIkKj13Q?si=OfGvIq2o-1ibPftP', 'Estadio Santiago Bernabéu', 'Real Madrid, Sporting de Lisboa', 'Champions League', '90', 'Fase de grupos de la Champions League 2017. Partido 1/6', 'Cristiano Ronaldo, Bryan Ruiz, Karim Benzema, Rui Patrício');




INSERT INTO chat_community (nombre_comunidad, descripcion, fecha_creacion, created_by_email, url_image) 
VALUES ('Comunidad de Formula 1', '¡Únete para discutir sobre las últimas noticias, carreras, pilotos y todo lo relacionado con la Fórmula 1!', '2023-12-31', 'david@gmail.com', 'images/Comunidades/f1_logo.png');

INSERT INTO chat_community (nombre_comunidad, descripcion, fecha_creacion, created_by_email, url_image) 
VALUES ('Comunidad de Fútbol', '¡Únete para debatir sobre partidos, equipos, jugadores y todo lo relacionado con el mundo del fútbol!', '2023-12-31', 'david@gmail.com', 'images/Comunidades/futbol_logo.png');

INSERT INTO chat_community (nombre_comunidad, descripcion, fecha_creacion, created_by_email, url_image) 
VALUES ('Comunidad de Peliculas', '¡Únete para conversar sobre las últimas películas, actores, directores y todo lo relacionado con el cine!', '2023-12-31', 'david@gmail.com', 'images/Comunidades/peliculas_logo.png');
